# Generated by Django 2.2.4 on 2022-09-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='releasedate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
