# Generated by Django 2.2.4 on 2022-09-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_app', '0004_auto_20220928_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeeksModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
