# Generated by Django 2.2.4 on 2022-09-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_app', '0007_auto_20220928_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.GenericIPAddressField(unique=True)),
            ],
        ),
    ]
