# Generated by Django 2.2.4 on 2022-09-26 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_book_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='books',
            new_name='book',
        ),
    ]
