# Generated by Django 2.2.4 on 2022-09-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_auto_20220926_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='note',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
