# Generated by Django 2.2.4 on 2022-10-04 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fav_book', '0002_book_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='uploaded_by',
            new_name='user',
        ),
    ]
