# Generated by Django 2.2.4 on 2022-10-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fav_book', '0003_auto_20221004_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ManyToManyField(related_name='favorites1', to='fav_book.User'),
        ),
    ]
