# Generated by Django 2.2.4 on 2022-10-05 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fav_book', '0004_auto_20221004_2018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
